#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
echo "Running linter..."
npm run lint
RESULT_LINT=$?
if [ $RESULT_LINT -ne 0 ]; then
	echo "Lint failed. Aborting commit."
	exit 1
fi

# Run tests
echo "Running tests..."
npm test
RESULT_TEST=$?
if [ $RESULT_TEST -ne 0 ]; then
	echo "Tests failed. Aborting commit."
	exit 1
fi

echo "All checks passed. Proceeding with commit."
